import type { Database, Role, Submission } from "./types";

/**
 * Demo content. The store falls back to this whenever the data file is
 * missing, so a fresh clone has something to browse straight away.
 */
const roles: Role[] = [
  {
    id: "rol_saltmarsh_nell",
    slug: "nell-saltmarsh",
    title: "NELL — Lead",
    production: "Saltmarsh",
    productionType: "Feature Film",
    synopsis:
      "A low-budget feature about a marine biologist who returns to the Essex coast to close her late father's boatyard and finds the tide has taken more than the land.",
    characterBrief:
      "Nell is guarded, funny in a way that keeps people at arm's length, and quietly furious about a childhood nobody else remembers the same way. She carries most of the film. We are open on ethnicity and looking for someone who can hold long silences without filling them.",
    requirements: [
      "Confident in and around open water",
      "Comfortable with three weeks on location in Essex",
      "Native or fluent English; regional accents welcome",
    ],
    location: "Essex, UK",
    selfTape: true,
    ageMin: 28,
    ageMax: 40,
    payType: "Paid",
    rate: "£950/week + accommodation and travel",
    unionStatus: "Either",
    shootDates: "12 Oct – 6 Nov 2026",
    deadline: "2026-09-18",
    castingDirector: "Priya Raman",
    company: "Raman Casting",
    disclaimer: "",
    postedAt: "2026-08-24T09:15:00.000Z",
  },
  {
    id: "rol_saltmarsh_gethin",
    slug: "gethin-saltmarsh",
    title: "GETHIN — Supporting",
    production: "Saltmarsh",
    productionType: "Feature Film",
    synopsis:
      "A low-budget feature about a marine biologist who returns to the Essex coast to close her late father's boatyard and finds the tide has taken more than the land.",
    characterBrief:
      "Gethin ran the boatyard alongside Nell's father for twenty years and has decided, without telling anyone, that he is going to keep it running. Warm, stubborn, physically at ease. Welsh accent preferred but not essential.",
    requirements: [
      "Comfortable working on and around boats",
      "Available for a two-week block",
    ],
    location: "Essex, UK",
    selfTape: true,
    ageMin: 55,
    ageMax: 70,
    payType: "Paid",
    rate: "£950/week + accommodation and travel",
    unionStatus: "Either",
    shootDates: "19 Oct – 1 Nov 2026",
    deadline: "2026-09-18",
    castingDirector: "Priya Raman",
    company: "Raman Casting",
    disclaimer: "",
    postedAt: "2026-08-24T09:22:00.000Z",
  },
  {
    id: "rol_northbank_dcelliot",
    slug: "dc-elliot-northbank",
    title: "DC AMARA ELLIOT — Series Regular",
    production: "Northbank",
    productionType: "TV Series",
    synopsis:
      "Series two of the returning crime drama set across the Manchester canal network. Eight episodes.",
    characterBrief:
      "Amara transferred in from Merseyside and is the only person in the room who thinks the case is already solved. Precise, dry, allergic to small talk. This is a full series arc across all eight episodes.",
    requirements: [
      "Available for the full block, Jan – Apr 2027",
      "Northern English accent",
      "Previous broadcast credit preferred",
    ],
    location: "Manchester, UK",
    selfTape: true,
    ageMin: 30,
    ageMax: 42,
    payType: "Paid",
    rate: "Equity broadcast rates, negotiable on experience",
    unionStatus: "Union",
    shootDates: "Jan – Apr 2027",
    deadline: "2026-10-02",
    castingDirector: "Tom Whitcombe",
    company: "Whitcombe & Fry Casting",
    disclaimer: "",
    postedAt: "2026-08-19T14:40:00.000Z",
  },
  {
    id: "rol_northbank_supporting",
    slug: "kez-northbank",
    title: "KEZ — Recurring",
    production: "Northbank",
    productionType: "TV Series",
    synopsis:
      "Series two of the returning crime drama set across the Manchester canal network. Eight episodes.",
    characterBrief:
      "Kez works the lock gates and sees everything. Appears in four of eight episodes. Non-professionals with the right instincts are genuinely welcome to submit for this one.",
    requirements: ["Manchester-based or able to work as a local"],
    location: "Manchester, UK",
    selfTape: true,
    ageMin: 18,
    ageMax: 25,
    payType: "Paid",
    rate: "£420/day",
    unionStatus: "Either",
    shootDates: "Feb – Mar 2027",
    deadline: "2026-10-02",
    castingDirector: "Tom Whitcombe",
    company: "Whitcombe & Fry Casting",
    disclaimer: "",
    postedAt: "2026-08-19T14:52:00.000Z",
  },
  {
    id: "rol_hearth_couple",
    slug: "couple-hearth",
    title: "COUPLE (x2) — Principal",
    production: "Hearth — Winter Campaign",
    productionType: "Commercial",
    synopsis:
      "A national television and online campaign for a home energy brand. One 60s hero film plus cutdowns.",
    characterBrief:
      "Two people who have clearly lived in the same house for a long time. We want real warmth and real ease rather than polish. Submitting as an established pair is welcome; note it in your cover message.",
    requirements: [
      "Usage: UK, all media, 12 months",
      "Buyout negotiated separately from the day rate",
      "One-day shoot plus a half-day fitting",
    ],
    location: "London, UK",
    selfTape: true,
    ageMin: 60,
    ageMax: 78,
    payType: "Paid",
    rate: "£1,200/day + buyout",
    unionStatus: "Either",
    shootDates: "22 Sep 2026",
    deadline: "2026-09-08",
    castingDirector: "Lena Ortiz",
    company: "Ortiz Casting",
    disclaimer:
      "Usage is UK, all media, 12 months from first air date. The day rate does not include the buyout, which is negotiated separately once you are cast. Submitting does not create any engagement, and we cannot pay for self-tapes. We keep your details for the duration of this casting and delete them within 6 months of it closing.",
    postedAt: "2026-08-27T11:05:00.000Z",
  },
  {
    id: "rol_glasshouse_vo",
    slug: "narrator-glasshouse",
    title: "NARRATOR — Voice",
    production: "The Glasshouse",
    productionType: "Voice Over",
    synopsis:
      "A six-part audio documentary series about the last commercial nursery in a Midlands town.",
    characterBrief:
      "The narrator is not a presenter. We want somebody who sounds like they are telling you something across a kitchen table, not reading it. All accents and backgrounds encouraged.",
    requirements: [
      "Broadcast-quality home booth, or able to record in Birmingham",
      "Roughly six half-day sessions across the run",
    ],
    location: "Remote / Birmingham, UK",
    selfTape: true,
    ageMin: 25,
    ageMax: 75,
    payType: "Paid",
    rate: "£300 per session",
    unionStatus: "Either",
    shootDates: "Nov 2026 – Jan 2027",
    deadline: "2026-09-25",
    castingDirector: "Ruth Adeyemi",
    company: "Sixth Floor Audio",
    disclaimer: "",
    postedAt: "2026-08-29T08:30:00.000Z",
  },
  {
    id: "rol_lantern_ensemble",
    slug: "ensemble-lantern",
    title: "ENSEMBLE (x6) — Company",
    production: "Lantern",
    productionType: "Theatre",
    synopsis:
      "A new devised piece touring mid-scale venues across the north of England in spring 2027.",
    characterBrief:
      "A company of six who will build the piece together over a five-week rehearsal period. Movement-led. We are casting for range and generosity in the room rather than for fixed characters.",
    requirements: [
      "Strong movement background",
      "Available for the full rehearsal period and tour",
      "Deaf and disabled performers particularly encouraged; access costs are budgeted",
    ],
    location: "Leeds, UK + UK tour",
    selfTape: false,
    ageMin: 21,
    ageMax: 55,
    payType: "Paid",
    rate: "ITC/Equity minimum + touring allowance",
    unionStatus: "Either",
    shootDates: "Rehearsals from 8 Feb 2027, tour to 30 May 2027",
    deadline: "2026-10-16",
    castingDirector: "Marcus Bell",
    company: "Lantern Theatre Company",
    disclaimer: "",
    postedAt: "2026-08-12T16:20:00.000Z",
  },
  {
    id: "rol_kestrel_youth",
    slug: "sam-kestrel",
    title: "SAM — Lead",
    production: "Kestrel",
    productionType: "Short Film",
    synopsis:
      "A fifteen-minute graduation short about a kid who finds an injured bird and decides not to tell anyone.",
    characterBrief:
      "Sam is eleven or twelve and does almost all of the film without dialogue. No previous experience needed. A chaperone is required on set and their travel is covered.",
    requirements: [
      "Chaperone required on set at all times",
      "Two consecutive weekends",
      "Comfortable outdoors in cold weather",
    ],
    location: "Peak District, UK",
    selfTape: true,
    ageMin: 11,
    ageMax: 13,
    payType: "Paid",
    rate: "£150/day + expenses",
    unionStatus: "Non-Union",
    shootDates: "7–8 and 14–15 Nov 2026",
    deadline: "2026-09-30",
    castingDirector: "Jo Fenwick",
    company: "Northern Film School",
    disclaimer:
      "This role is for a performer under 16. A parent or guardian must submit on their behalf and must be present for every day of the shoot. A licence from the local authority is required before filming and we will apply for it once the role is cast.",
    postedAt: "2026-08-22T13:00:00.000Z",
  },
];

const submissions: Submission[] = [
  {
    id: "sub_0001",
    roleId: "rol_saltmarsh_nell",
    name: "Aoife Brennan",
    email: "aoife.brennan@example.com",
    phone: "07700 900142",
    location: "London, UK",
    age: 33,
    unionStatus: "Union",
    reelUrl: "https://vimeo.com/example/aoife-brennan-reel",
    profileUrl: "https://spotlight.com/example/aoife-brennan",
    coverNote:
      "I grew up on the Blackwater estuary and have spent more of my life in a boat than out of one. The long silences in the brief are what made me want to submit.",
    status: "Shortlisted",
    acceptedTerms: null,
    acceptedAt: null,
    submittedAt: "2026-08-25T10:12:00.000Z",
  },
  {
    id: "sub_0002",
    roleId: "rol_saltmarsh_nell",
    name: "Deborah Okonkwo",
    email: "d.okonkwo@example.com",
    phone: "07700 900318",
    location: "Bristol, UK",
    age: 36,
    unionStatus: "Union",
    reelUrl: "https://vimeo.com/example/d-okonkwo",
    profileUrl: "https://spotlight.com/example/d-okonkwo",
    coverNote:
      "Most recently on stage at the Old Vic. I can send an additional self-tape on water at short notice if useful.",
    status: "Callback",
    acceptedTerms: null,
    acceptedAt: null,
    submittedAt: "2026-08-25T18:44:00.000Z",
  },
  {
    id: "sub_0003",
    roleId: "rol_saltmarsh_nell",
    name: "Marta Kowalczyk",
    email: "marta.k@example.com",
    phone: "07700 900771",
    location: "Manchester, UK",
    age: 29,
    unionStatus: "Non-Union",
    reelUrl: "https://vimeo.com/example/marta-kowalczyk",
    profileUrl: "",
    coverNote:
      "First feature submission. I have three shorts on my reel, the last of which played Encounters.",
    status: "New",
    acceptedTerms: null,
    acceptedAt: null,
    submittedAt: "2026-08-28T07:59:00.000Z",
  },
  {
    id: "sub_0004",
    roleId: "rol_saltmarsh_gethin",
    name: "Dai Llewellyn",
    email: "dai.llewellyn@example.com",
    phone: "07700 900255",
    location: "Cardiff, UK",
    age: 63,
    unionStatus: "Union",
    reelUrl: "https://vimeo.com/example/dai-llewellyn",
    profileUrl: "https://spotlight.com/example/dai-llewellyn",
    coverNote:
      "Welsh, and I have restored two wooden boats badly enough to know how it is done properly.",
    status: "Shortlisted",
    acceptedTerms: null,
    acceptedAt: null,
    submittedAt: "2026-08-26T09:03:00.000Z",
  },
  {
    id: "sub_0005",
    roleId: "rol_northbank_dcelliot",
    name: "Simone Achebe",
    email: "simone.achebe@example.com",
    phone: "07700 900604",
    location: "Liverpool, UK",
    age: 38,
    unionStatus: "Union",
    reelUrl: "https://vimeo.com/example/simone-achebe",
    profileUrl: "https://spotlight.com/example/simone-achebe",
    coverNote:
      "Two series regular credits, both northern. Free for the whole block from January.",
    status: "New",
    acceptedTerms: null,
    acceptedAt: null,
    submittedAt: "2026-08-21T12:30:00.000Z",
  },
  {
    id: "sub_0006",
    roleId: "rol_northbank_dcelliot",
    name: "Hannah Pryce",
    email: "hannah.pryce@example.com",
    phone: "07700 900019",
    location: "Sheffield, UK",
    age: 41,
    unionStatus: "Union",
    reelUrl: "https://vimeo.com/example/hannah-pryce",
    profileUrl: "https://spotlight.com/example/hannah-pryce",
    coverNote: "Sheffield born. Tape attached, second take is the one.",
    status: "Declined",
    acceptedTerms: null,
    acceptedAt: null,
    submittedAt: "2026-08-20T16:15:00.000Z",
  },
  {
    id: "sub_0007",
    roleId: "rol_hearth_couple",
    name: "Ken & Barbara Whitfield",
    email: "whitfields@example.com",
    phone: "07700 900488",
    location: "Croydon, UK",
    age: 71,
    unionStatus: "Non-Union",
    reelUrl: "",
    profileUrl: "",
    coverNote:
      "Submitting as a pair, married 46 years. We have done two commercials together, both as a couple.",
    status: "Shortlisted",
    acceptedTerms:
      "Usage is UK, all media, 12 months from first air date. The day rate does not include the buyout, which is negotiated separately once you are cast. Submitting does not create any engagement, and we cannot pay for self-tapes. We keep your details for the duration of this casting and delete them within 6 months of it closing.",
    acceptedAt: "2026-08-28T14:22:00.000Z",
    submittedAt: "2026-08-28T14:22:00.000Z",
  },
  {
    id: "sub_0008",
    roleId: "rol_glasshouse_vo",
    name: "Errol Vance",
    email: "errol.vance@example.com",
    phone: "07700 900930",
    location: "Birmingham, UK",
    age: 58,
    unionStatus: "Union",
    reelUrl: "https://soundcloud.com/example/errol-vance-reel",
    profileUrl: "",
    coverNote:
      "Home booth, Source Connect if you need it. Brummie, and unapologetic about it.",
    status: "New",
    acceptedTerms: null,
    acceptedAt: null,
    submittedAt: "2026-08-30T09:48:00.000Z",
  },
];

export function seedDatabase(): Database {
  return {
    roles: structuredClone(roles),
    submissions: structuredClone(submissions),
  };
}
